[package]
name = "generator"
version = "0.2.0"
edition = "2024"

[dependencies]
pulldown-cmark = "0.13"
chrono = "0.4.43"
image = "0.25.9"
rayon = "1.11.0"
thiserror = "2.0"

[dev-dependencies]
tempfile = "3.15"
